spring:
  rabbitmq:
    host: "${RABBITMQ_HOST:rabbitmq}"
    port: "${RABBITMQ_PORT:5672}"
    username: "${RABBITMQ_USERNAME:${RABBITMQ_DEFAULT_USER:guest}}"
    password: "${RABBITMQ_PASSWORD:${RABBITMQ_DEFAULT_PASS:guest}}"

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
