server:
  port: 8089
  forward-headers-strategy: framework

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "${AUTH0_ISSUER_URI:https://dev-e5ik5gbwpzkcqfrw.us.auth0.com/}"

auth0:
  audience: "${AUTH0_AUDIENCE:https://api.coboxsv.dev}"

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: false
