spring:
  application:
    name: fleet-service
  cloud:
    openfeign:
      okhttp:
        enabled: true
  config:
    import: "optional:configserver:http://config-service:8888"
  rabbitmq:
    host: "${RABBITMQ_HOST:rabbitmq}"
    port: "${RABBITMQ_PORT:5672}"
    username: "${RABBITMQ_USERNAME:${RABBITMQ_DEFAULT_USER:guest}}"
    password: "${RABBITMQ_PASSWORD:${RABBITMQ_DEFAULT_PASS:guest}}"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "${AUTH0_ISSUER_URI:https://dev-e5ik5gbwpzkcqfrw.us.auth0.com/}"

auth0:
  audience: "${AUTH0_AUDIENCE:https://api.coboxsv.dev}"

management:
  health:
    rabbit:
      enabled: false
