spring:
  application:
    name: report-service
  config:
    import: "optional:configserver:http://config-service:8888"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "${AUTH0_ISSUER_URI:https://dev-e5ik5gbwpzkcqfrw.us.auth0.com/}"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 10
        order_inserts: true
        order_updates: true
  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 600000
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: "${RABBITMQ_USERNAME:${RABBITMQ_DEFAULT_USER:guest}}"
    password: "${RABBITMQ_PASSWORD:${RABBITMQ_DEFAULT_PASS:guest}}"
    connection-timeout: 5000
    listener:
      simple:
        acknowledge-mode: auto
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 5000

auth0:
  audience: "${AUTH0_AUDIENCE:https://api.coboxsv.dev}"

server:
  port: ${SERVER_PORT:8091}
  servlet:
    context-path: /

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  health:
    rabbit:
      enabled: false
